services:
  - type: web
    name: task-manager-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      ./build.sh
    startCommand: gunicorn task_manager_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
      - key: DEBUG
      - key: BASE_URL
      - key: ALLOWED_HOSTS
      - key: BREVO_API_KEY
      - key: BREVO_EMAIL
