# Generated by Django 5.2.6 on 2025-09-16 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "ADMIN"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPERADMIN", "SuperAdmin"),
                    ("ADMIN", "Admin"),
                    ("USER", "User"),
                ],
                default="USER",
                max_length=20,
            ),
        ),
    ]
